import 'package:flutter/material.dart';

class AppTheme {
  // Light mode colors
  static const Color lightBackground = Color(0xFFF8FAFC);
  static const Color lightCard = Colors.white;
  static const Color lightPrimaryText = Colors.black;
  static const Color lightSecondaryText = Color(0xFF757575); // Colors.grey.shade600
  static const Color lightTertiaryText = Color.fromRGBO(97, 97, 97, 1);
  static const Color lightIcon = Colors.grey;
  static const Color lightBorder = Color(0xFFF5F5F5); // Colors.grey.shade100
  static const Color lightButton = Colors.blue;
  static const Color lightRating = Color(0xFFF59E0B);
  static const Color lightProgressBackground = Color.fromRGBO(238, 238, 238, 1);
  static const Color lightProgressValue = Color(0xFFF59E0B);
  static const Color lightSnackBarError = Color(0xFFDC2626);
  static const Color lightSnackBarSuccess = Color(0xFF10B981);
  static const Color lightDisabled = Color.fromRGBO(189, 189, 189, 1);
  static const Color lightDetailBackground = Color(0xFFFAFAFA); // Colors.grey.shade50
  static const Color lightAccentPurple = Color(0xFF6366F1);
  static const Color lightAccentPurpleVariant = Color(0xFF8B5CF6);
  static const Color lightAccentCyan = Color(0xFF0EA5E9);
  static const Color lightAccentPink = Color(0xFFEC4899);
  static const Color lightErrorLight = Color(0xFFFECACA);
  static const Color lightErrorLightBackground = Color(0xFFFEE2E2);
  static const Color lightDivider = Color(0xFFE0E0E0); // Colors.grey.shade200
  static const Color lightSwitchInactive = Color(0xFFE0E0E0); // Colors.grey.shade300
  static const Color lightTextDark = Color(0xFF424242); // Colors.grey.shade800
  static const Color lightTextMedium = Color(0xFF616161); // Colors.black87
  static const Color lightTextGrey = Color(0xFF9E9E9E); // Colors.grey
  static const Color lightAccentBlue = Color(0xFF1976D2); // Colors.blue[700]
  static const Color lightAccentBlueLight = Color(0xFFBBDEFB); // Colors.blue[50]
  static const Color lightAccentBlueDark = Color(0xFF1565C0); // Colors.blue[600]
  static const Color lightAccentPurpleDark = Color(0xFF7B1FA2); // Colors.purple[600]
  static const Color lightAccentPurpleLight = Color(0xFFAB47BC); // Colors.purple[400]
  static const Color lightAccentTeal = Color(0xFF00796B); // Colors.teal[600]
  static const Color lightAccentRedLight = Color(0xFFFFEBEE); // Colors.red.shade50
  static const Color lightAccentRedDark = Color(0xFFB71C1C); // Colors.red[900]

  // Dark mode colors
  static const Color darkBackground = Color(0xFF121212);
  static const Color darkCard = Color(0xFF1E1E1E);
  static const Color darkPrimaryText = Colors.white;
  static const Color darkSecondaryText = Color.fromRGBO(158, 158, 158, 1); // Approximates Colors.grey.shade400
  static const Color darkTertiaryText = Color.fromRGBO(158, 158, 158, 1);
  static const Color darkIcon = Color.fromRGBO(117, 117, 117, 1);
  static const Color darkBorder = Color(0xFF333333);
  static const Color darkButton = Colors.blue;
  static const Color darkRating = Color.fromRGBO(255, 215, 0, 1);
  static const Color darkProgressBackground = Color.fromRGBO(66, 66, 66, 1);
  static const Color darkProgressValue = Color.fromRGBO(255, 215, 0, 1);
  static const Color darkSnackBarError = Color(0xFFDC2626);
  static const Color darkSnackBarSuccess = Color(0xFF10B981);
  static const Color darkDisabled = Color.fromRGBO(97, 97, 97, 1);
  static const Color darkDetailBackground = Color(0xFF252525);
  static const Color darkInfoBackground = Color(0xFF424242);
  static const Color darkAccentPurple = Color(0xFF6366F1);
  static const Color darkAccentPurpleVariant = Color(0xFF8B5CF6);
  static const Color darkAccentCyan = Color(0xFF0EA5E9);
  static const Color darkAccentPink = Color(0xFFEC4899);
  static const Color darkErrorLight = Color(0xFFFECACA);
  static const Color darkErrorLightBackground = Color(0xFFFEE2E2);
  static const Color darkDivider = Color(0xFF424242); // Colors.grey.shade800
  static const Color darkSwitchInactive = Color(0xFF616161); // Colors.grey.shade600
  static const Color darkTextDark = Color(0xFF424242);
  static const Color darkTextMedium = Color(0xFF616161);
  static const Color darkTextGrey = Color(0xFF9E9E9E);
  static const Color darkAccentBlue = Color(0xFF0277BD); // Colors.blue[800]
  static const Color darkAccentBlueLight = Color(0xFF90CAF9); // Colors.blue[200]
  static const Color darkAccentBlueDark = Color(0xFF1565C0); // Colors.blue[600]
  static const Color darkAccentPurpleDark = Color(0xFF7B1FA2); // Colors.purple[600]
  static const Color darkAccentPurpleLight = Color(0xFFAB47BC); // Colors.purple[400]
  static const Color darkAccentTeal = Color(0xFF00796B); // Colors.teal[600]
  static const Color darkAccentRedLight = Color(0xFFCF6679); // Colors.red.shade50 equivalent
  static const Color darkAccentRedDark = Color(0xFFB71C1C); // Colors.red[900]

  // Get colors based on dark mode
  static Color getBackground(bool isDarkMode) => isDarkMode ? darkBackground : lightBackground;
  static Color getCard(bool isDarkMode) => isDarkMode ? darkCard : lightCard;
  static Color getPrimaryText(bool isDarkMode) => isDarkMode ? darkPrimaryText : lightPrimaryText;
  static Color getSecondaryText(bool isDarkMode) => isDarkMode ? darkSecondaryText : lightSecondaryText;
  static Color getTertiaryText(bool isDarkMode) => isDarkMode ? darkTertiaryText : lightTertiaryText;
  static Color getIcon(bool isDarkMode) => isDarkMode ? darkIcon : lightIcon;
  static Color getBorder(bool isDarkMode) => isDarkMode ? darkBorder : lightBorder;
  static Color getButton(bool isDarkMode) => isDarkMode ? darkButton : lightButton;
  static Color getRating(bool isDarkMode) => isDarkMode ? darkRating : lightRating;
  static Color getProgressBackground(bool isDarkMode) => isDarkMode ? darkProgressBackground : lightProgressBackground;
  static Color getProgressValue(bool isDarkMode) => isDarkMode ? darkProgressValue : lightProgressValue;
  static Color getSnackBarError(bool isDarkMode) => isDarkMode ? darkSnackBarError : lightSnackBarError;
  static Color getSnackBarSuccess(bool isDarkMode) => isDarkMode ? darkSnackBarSuccess : lightSnackBarSuccess;
  static Color getDisabled(bool isDarkMode) => isDarkMode ? darkDisabled : lightDisabled;
  static Color getDetailBackground(bool isDarkMode) => isDarkMode ? darkDetailBackground : lightDetailBackground;
  static Color getInfoBackground(bool isDarkMode) => isDarkMode ? darkInfoBackground : lightBorder;
  static Color getAccentPurple(bool isDarkMode) => isDarkMode ? darkAccentPurple : lightAccentPurple;
  static Color getAccentPurpleVariant(bool isDarkMode) => isDarkMode ? darkAccentPurpleVariant : lightAccentPurpleVariant;
  static Color getAccentCyan(bool isDarkMode) => isDarkMode ? darkAccentCyan : lightAccentCyan;
  static Color getAccentPink(bool isDarkMode) => isDarkMode ? darkAccentPink : lightAccentPink;
  static Color getErrorLight(bool isDarkMode) => isDarkMode ? darkErrorLight : lightErrorLight;
  static Color getErrorLightBackground(bool isDarkMode) => isDarkMode ? darkErrorLightBackground : lightErrorLightBackground;
  static Color getDivider(bool isDarkMode) => isDarkMode ? darkDivider : lightDivider;
  static Color getSwitchInactive(bool isDarkMode) => isDarkMode ? darkSwitchInactive : lightSwitchInactive;
  static Color getTextDark(bool isDarkMode) => isDarkMode ? darkTextDark : lightTextDark;
  static Color getTextMedium(bool isDarkMode) => isDarkMode ? darkTextMedium : lightTextMedium;
  static Color getTextGrey(bool isDarkMode) => isDarkMode ? darkTextGrey : lightTextGrey;
  static Color getAccentBlue(bool isDarkMode) => isDarkMode ? darkAccentBlue : lightAccentBlue;
  static Color getAccentBlueLight(bool isDarkMode) => isDarkMode ? darkAccentBlueLight : lightAccentBlueLight;
  static Color getAccentBlueDark(bool isDarkMode) => isDarkMode ? darkAccentBlueDark : lightAccentBlueDark;
  static Color getAccentPurpleDark(bool isDarkMode) => isDarkMode ? darkAccentPurpleDark : lightAccentPurpleDark;
  static Color getAccentPurpleLight(bool isDarkMode) => isDarkMode ? darkAccentPurpleLight : lightAccentPurpleLight;
  static Color getAccentTeal(bool isDarkMode) => isDarkMode ? darkAccentTeal : lightAccentTeal;
  static Color getAccentRedLight(bool isDarkMode) => isDarkMode ? darkAccentRedLight : lightAccentRedLight;
  static Color getAccentRedDark(bool isDarkMode) => isDarkMode ? darkAccentRedDark : lightAccentRedDark;
}